{
 "title": "Calico",
 "tags": [
  "Calico",
  "CNI"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.99,sum(irate(process_cpu_seconds_total{pod=~\"calico-node-.*\"}[5m]))by(pod))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg (container_memory_working_set_bytes{pod=~\"calico-node-.*\", namespace=\"kube-system\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Hosts",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(felix_host)" }
   ]
  },
  {
   "title": "Active Local Endpoints",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "felix_active_local_endpoints", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Exec Time p99",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rate(felix_exec_time_micros{quantile=\"0.99\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Dataplane", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Update Apply Duration p99",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(felix_int_dataplane_apply_time_seconds{quantile=\"0.99\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Update Failures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(felix_int_dataplane_failures[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Message Types",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(felix_int_dataplane_messages[5m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Message Batch Sizes p99",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(felix_int_dataplane_msg_batch_size{quantile=\"0.99\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "iptables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Active Chains",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(felix_iptables_chains) by (table)",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Active Rules",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(felix_iptables_rules) by (table)",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Lines Executed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (table) (increase(felix_iptables_lines_executed[5m]))",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(felix_iptables_save_calls[5m]))",
     "legendFormat": "Save"
    },
    {
     "expr": "sum(rate(felix_iptables_restore_calls[5m]))",
     "legendFormat": "Restore"
    }
   ]
  },
  {
   "title": "Save Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(felix_iptables_save_errors[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Restore Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(felix_iptables_restore_errors[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}