apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqubes-pvc
  namespace: sonarqube
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  storageClassName: "longhorn"
