apiVersion: v1
kind: Service
metadata:
  name: leedh-service
  labels:
    env: prod
spec:
  type: NodePort
  selector:
    app: leedh-test-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

