patchesStrategicMerge:
- deployment-bluegreen.yaml
- service-bluegreen.yaml
images:
- name: harbor.eks.leedh.cloud/cicd/test-app
  newTag: "93"
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
