output "cluster_id" {
  description = "EKS cluster ID."
  value       = module.eks.cluster_id
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks.config_map_aws_auth
}

output "cluster_name" {
  description = "Kubernetes Cluster Name"
  value       = var.cluster_name
}

output "key_pair_key_pair_id" {
  value       = module.key_pair.key_pair_id
  description = "aws key pair  ID"
}

output "key_pair_key_name" {
  description = "aws key pair Name"
  value       = module.key_pair.key_pair_name
}

output "ssh_key" {
  description = "ssh key generated by terraform"
  value       = tls_private_key.this.private_key_pem
  sensitive   = true
}
