apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem          
  capacity:
    storage: 20Gi
  hostPath:
    path: "/mnt/data"
