pipeline {
    environment {
        GIT_SSL_NO_VERIFY = 0
        REGISTRY = "harbor.eks.leedh.cloud"
        IMAGENAME = "cicd/test-app"
        GITLAB_API_TOKEN = credentials('GITLAB_API_TOKEN')
    }
  agent {
    kubernetes {
      label 'my-test-app-cicd'
      yamlFile 'cicd-template.yaml'
    }
  }
  
    stages {
       stage('Maven Source Code Build') {
          steps {
            container('maven') {
              echo "Check Maven"
              sh 'mvn -version'
              echo "Start Maven Build"
              sh 'mvn clean install'
              sh 'ls -al ./target'
            }
          }
        }
        stage('Build Docker Image') {
          steps {
            container('docker') {
              sh 'docker build -t $REGISTRY/$IMAGENAME:$BUILD_NUMBER .'
              sh 'docker images | grep $IMAGENAME'
            }
          }
        }
        stage('Push Docker Image Harbor') {
          steps {
            container('docker') {
              sh 'echo $HARBOR_PASSWORD | docker login -u$HARBOR_ID --password-stdin $REGISTRY'
              sh 'docker push $REGISTRY/$IMAGENAME:$BUILD_NUMBER'
            }
          }
        }
        stage('Local Docker Image Delete') {
          steps {
            container('docker') {
              sh 'IMAGE=$(docker images | grep $IMAGENAME | grep $BUILD_NUMBER)'
              sh """
                  docker images | grep $IMAGENAME | grep $BUILD_NUMBER | awk \'{print \$3}\' | xargs docker rmi -f
                 """
            }
          }
        }
        stage('Deploy') {
          steps {
            container('deploy') {
              sh 'export GIT_SSL_NO_VERIFY=0'
              sh 'git pull origin main'
              sh 'echo $GITLAB_API_TOKEN'
              sh 'git config --global user.email "leedh@test.com"'
              sh 'git checkout main'
              sh 'cd manifest/dev && kustomize edit set image harbor.eks.leedh.cloud/cicd/test-app:$BUILD_NUMBER'
              sh 'git add .'
              sh 'git commit -a -m "updated test"'
              sh 'git push https://$GITLAB_API_TOKEN:$GITLAB_API_TOKEN@gitlab.eks.leedh.cloud/root/my-test.git'
            }
          }
        }
    }
}
