apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2Rldi1rdWJlLWhhcmJvci5qb2lucy5uZXQiOnsidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3Jxxxx6IllXUnRhVzQ2SVVBaGVHeGtjR1JzT0RVPSJ9fX0=
kind: Secret
metadata:
  name: {{ .Release.Name }}-registry
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson

