---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-service
  labels:
    app: {{ $.Release.Name }}-service
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ $.Release.Name }}-deployment
    release: {{ .Release.Name }}

